spring.application.name=notificationemail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saber11noreply@gmail.com
spring.mail.password=cmek yaod aqce evhz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true