spring:
  application:
    name: exam
  datasource:
    url: jdbc:postgresql://localhost:5432/saber111
    username: postgres
    password: David1470
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          format_sql: true


